/**
 * CCS Remote - Configuration management
 */

import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'js-yaml';
import { ServerConfig } from './types';

const DEFAULT_CONFIG: ServerConfig = {
  port: 8318,
  host: '0.0.0.0',
  dataDir: '/app/data',
  apiKey: 'ccs-remote-key',
  managementKey: 'ccs-remote-mgmt',
  cliproxyPort: 8317,
  corsOrigins: ['*'],
};

let cachedConfig: ServerConfig | null = null;

/**
 * Get data directory path (from env or config)
 */
export function getDataDir(): string {
  return process.env.CCS_DATA_DIR || cachedConfig?.dataDir || DEFAULT_CONFIG.dataDir;
}

/**
 * Get auth directory path
 */
export function getAuthDir(): string {
  return path.join(getDataDir(), 'cliproxy', 'auth');
}

/**
 * Get CLIProxy config directory
 */
export function getCliproxyDir(): string {
  return path.join(getDataDir(), 'cliproxy');
}

/**
 * Get CLIProxy binary directory
 */
export function getBinDir(): string {
  return path.join(getCliproxyDir(), 'bin');
}

/**
 * Load configuration from file or environment
 */
export function loadConfig(): ServerConfig {
  if (cachedConfig) {
    return cachedConfig;
  }

  const config: ServerConfig = { ...DEFAULT_CONFIG };

  // Override from environment variables
  if (process.env.CCS_PORT) {
    config.port = parseInt(process.env.CCS_PORT, 10);
  }
  if (process.env.CCS_HOST) {
    config.host = process.env.CCS_HOST;
  }
  if (process.env.CCS_DATA_DIR) {
    config.dataDir = process.env.CCS_DATA_DIR;
  }
  if (process.env.CCS_API_KEY) {
    config.apiKey = process.env.CCS_API_KEY;
  }
  if (process.env.CCS_MANAGEMENT_KEY) {
    config.managementKey = process.env.CCS_MANAGEMENT_KEY;
  }
  if (process.env.CCS_CLIPROXY_PORT) {
    config.cliproxyPort = parseInt(process.env.CCS_CLIPROXY_PORT, 10);
  }
  if (process.env.CCS_CORS_ORIGINS) {
    config.corsOrigins = process.env.CCS_CORS_ORIGINS.split(',').map((s) => s.trim());
  }

  // Try to load from YAML config file
  const configPath = path.join(getDataDir(), 'config.yaml');
  if (fs.existsSync(configPath)) {
    try {
      const content = fs.readFileSync(configPath, 'utf-8');
      const yamlConfig = yaml.load(content) as Partial<ServerConfig>;
      Object.assign(config, yamlConfig);
    } catch (error) {
      console.warn(`[config] Failed to load ${configPath}:`, error);
    }
  }

  cachedConfig = config;
  return config;
}

/**
 * Generate CLIProxy config.yaml file
 */
export function generateCliproxyConfig(): string {
  const config = loadConfig();
  const authDir = getAuthDir().replace(/\\/g, '/');

  const content = `# CLIProxyAPI config generated by CCS Remote
# Generated: ${new Date().toISOString()}

port: ${config.cliproxyPort}
debug: false

# Logging
logging-to-file: false
request-log: false

# Dashboard & Management
usage-statistics-enabled: true
remote-management:
  allow-remote: true
  secret-key: "${config.managementKey}"
  disable-control-panel: false

# Reliability
request-retry: 0
max-retry-interval: 0
quota-exceeded:
  switch-project: true
  switch-preview-model: true

# Authentication
api-keys:
  - "${config.apiKey}"

auth-dir: "${authDir}"
`;

  const configPath = path.join(getCliproxyDir(), 'config.yaml');
  fs.mkdirSync(path.dirname(configPath), { recursive: true });
  fs.writeFileSync(configPath, content, { mode: 0o600 });

  return configPath;
}

/**
 * Ensure data directories exist
 */
export function ensureDataDirs(): void {
  const dirs = [getDataDir(), getAuthDir(), getCliproxyDir(), getBinDir()];
  for (const dir of dirs) {
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true, mode: 0o700 });
    }
  }
}

